version: "3.9"

services:
  db:
    image: postgres:15
    container_name: smart_trip_db
    environment:
      POSTGRES_DB: smart_trip_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: smart_trip_backend
    command: gunicorn smart_trip.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=smart_trip.settings

volumes:
  postgres_data:
